name: Node CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Install NSIS
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install nsis
    - name: Print NSIS version
      run: makensis -VERSION

    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Setup NodeJS
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Dependencies Install
      run: npm ci
      env:
        CI: true

    - name: Build and Test
      run: npm run build
      env:
        CI: true

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: installer/Lyricsify_*_Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
